### ISSUE TITLE
Use the issuer field from the JWT payload

### ISSUE THREAD

**Issue by leplatrem** [mozilla/doorman#78]
Currently, we:

1. define a `jwtIssuer` in the service configuration
1. load public key for each jwt issuer on startup
1. verify the JWT for a specific service against the issuer specified in the configuration

It could make more sense to have:

1. Enable JWT by default
1. Read the issuer from the JWT payload (`iss`) 
1. Download the public keys (if necessary)
1. Verify the JWT against the iss

And have a more specific configuration field like `jwtDisabled` to disable JWT

**Comment by leplatrem** [comment]
This would still require to have a list of allowed issuers.

**Comment by leplatrem** [comment]
So this does not make sense actually.

**Comment by mostlygeek** [comment]
I think for the first version we should focus on supporting only JWTs. Using the `iss` field over `jwtIssuer` is also what we should do. +1 to your plan:


1. Enable JWT by default
1. Read the issuer from the JWT payload (iss)
1. Download the public keys (if necessary)
1. Verify the JWT against the iss

**Comment by mostlygeek** [comment]
Having a list of allowed issuers is a good security feature.  Is this something we already have?

**Comment by leplatrem** [comment]
I think we can stick to the current approach (with #82):

1. Define a JWT issuer per service
1. Download the public keys 
1. Verify the JWT payload against the issuer keys

The key verification will fail if JWT comes from somewhere than the issuer defined in the configuration. We could add a `if token.iss != jwtIssuer {return 401}` to save some computation but that's minor IMO

**Comment by leplatrem** [comment]
Closing since current approach is the way to go for verifying issuer.
