### ISSUE TITLE
Merge API and configuration documentation

### ISSUE THREAD

**Issue by leplatrem** [mozilla/doorman#84]

**Comment by leplatrem** [comment]
The spectacle tool I used only does API docs (https://mozilla.github.io/doorman/) . I'd like to have the configuration documentation (currently in README) and narrative examples (currently in examples/ folder) in a single place.

I could use Sphinx on readthedocs with this extension https://sphinxcontrib-openapi.readthedocs.io 
for example.

@peterbe @mostlygeek @Natim @glasserc @magopian do you have any idea or suggestions?

**Comment by glasserc** [comment]
No ideas or suggestions, but I think Sphinx plus a plugin seems sane.

**Comment by leplatrem** [comment]
I really like the minimalist style of sphinxcontrib-openapi but on the other hand it does not cover the specs fully (descriptions, schemas, ...)

https://sphinxcontrib-redoc.readthedocs.io is another option, it uses https://github.com/Rebilly/ReDoc
but it's far from minimalist :)

**Comment by peterbe** [comment]
No strong opinion or better suggestions.
That sphinxcontrib-openapi looks good.

I quite like the idea of sphinx as you can have separate `.rst` files and thus one page could be about the open API. 

But is it really that important? If integrators can read the openapi JSON directly, perhaps that has most of the things they need. The rest of the documentation, apart from some nice human introduction is all looked up by searching.
