### ISSUE TITLE
Split doorman package

### ISSUE THREAD

**Issue by leplatrem** [mozilla/doorman#86]
Suggested by Ben:
```
Splitting up the doorman package into:

- web handler / middleware package
- ladon middleware
- JWT package

Since they are in separate packages they can only interact with each other via the public interfaces.  This might force a cleaner design by default.
```

**Comment by leplatrem** [comment]
Currently every HTTP handlers are along their respective package (`__reload__` in config, `/allowed` in `doorman`, heartbeat etc. in `utilities`...)

I can see that moving all the handlers in the same `handlers` package would:
- allow to export a single handler (#64) 
- restrict Gin dependancy to a single place
- centralize the list of API URLs in one place 
- give a good reason to have public interfaces in the respective config and doorman package

@mostlygeek Do you think it's a good pattern to move every handlers into a single package (eg. `handlers`) ?

Thanks!

**Comment by mostlygeek** [comment]
> Do you think it's a good pattern to move every handlers into a single package (eg. handlers) ?

Yes.
