### ISSUE TITLE
(Mozilla-specific) Document how to refer to contractors as principals

### ISSUE THREAD

**Issue by leplatrem** [mozilla/doorman#97]
Will we obtain a `contractor` group from IdP, like we have for staff?

From https://github.com/mozilla/doorman/pull/93#pullrequestreview-92201852

**Comment by g-k** [comment]
cc @gdestuynder re: auth0 or the mozilla IAM has a separate group for contractors

**Comment by gdestuynder** [comment]
@leplatrem you should now see `hris_is_staff` for employees in `user.groups`
You can also see it for your own user on http://sso.mozilla.com/info

For contractors, see https://github.com/mozilla-iam/cis_hris_publisher/issues/12

**Comment by andrewkrug** [comment]
hris_workertype_$TYPE is in production!

**Comment by leplatrem** [comment]
Thanks for the update @andrewkrug !
